# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# Please consult the lectures
#        vector                         vs                      Matrix

#           1D                       ,                        2D

# only one column or row             ,                  multiple row or column

# like a single product info         ,            collection of all products info

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 

In [2]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [1]:
# To avoid overwriting the output, please code here 

In [ ]:
dataArray = np.array(list_1)
print(dataArray)
print(type(dataArray))
# print(dataArray.dtype)


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [7]:
# To avoid overwriting the output, please code here 

In [20]:
np.arange(0,6,1)
# np.arange(6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [9]:
# To avoid overwriting the output, please code here 

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [28]:
# To avoid overwriting the output, please code here 
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [29]:
# To avoid overwriting the output, please code here 
np.ones(5)

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [33]:
# To avoid overwriting the output, please code here 
np.full(5,10,dtype=float)

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [34]:
# To avoid overwriting the output, please code here 
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [38]:
# To avoid overwriting the output, please code here 
np.linspace(0,1,10,retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [39]:
# To avoid overwriting the output, please code here 
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
# To avoid overwriting the output, please code here 
a = np.arange(25)
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# To avoid overwriting the output, please code here 
a = np.arange(25)
a.shape = (5,5)
a
# yes we can use shape instead of reshape. But shape modify array permanantly,which reshape can't!

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [62]:
# To avoid overwriting the output, please code here 
a = np.arange(0.1,2.6,0.1)
a.reshape(5,5)


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [72]:
# To avoid overwriting the output, please code here 
a=np.linspace(0,24,25,dtype=int)
print(a.reshape(5,5))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

### "It seems the answer was accidentally provided in the comments."
#My answer
#arange(): Used when you know the specific distance/gap between each number.
# linspace():Used when you know exactly how many points you need between two numbers.

**15. How to generate a single random integer number using NumPy built-in function?**

In [32]:
# To avoid overwriting the output, please code here 

In [81]:
np.random.randint(100)

29

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [120]:
# To avoid overwriting the output, please code here 
rand_num = np.random.rand(7,5)

print(rand_num)

[[0.49647874 0.20265214 0.62783879 0.42880899 0.7227513 ]
 [0.22836171 0.03034058 0.58542791 0.18017461 0.62053926]
 [0.12619188 0.31153482 0.47159956 0.76954768 0.44548837]
 [0.82509789 0.52782449 0.6791474  0.94222644 0.36289481]
 [0.27227532 0.55224551 0.90349852 0.83484767 0.42668631]
 [0.68296752 0.71438084 0.86598506 0.98884042 0.89181923]
 [0.88501024 0.96180085 0.11888526 0.95719351 0.90191781]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [125]:
# To avoid overwriting the output, please code here 
np.identity(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 